version: 2
project_name: go-evaluator
release:
  github:
    owner: arran4
    name: go-evaluator
builds:
  - id: csvfilter
    main: ./cmd/csvfilter
    binary: csvfilter
  - id: jsonlfilter
    main: ./cmd/jsonlfilter
    binary: jsonlfilter
  - id: jsontest
    main: ./cmd/jsontest
    binary: jsontest
  - id: yamltest
    main: ./cmd/yamltest
    binary: yamltest

archives:
  - id: csvfilter
  - id: jsonlfilter
  - id: jsontest
  - id: yamltest

brews:
  - repository:
      owner: arran4
      name: homebrew-tap
    ids: [csvfilter, jsonlfilter, jsontest, yamltest]

nfpms:
  - package_name: "{{ .ProjectName }}-{{ .Build.ID }}"
    formats: [deb, rpm]
    maintainer: "Arran4 <arran4@users.noreply.github.com>"

snapcrafts:
  - name_template: "{{ .ProjectName }}-{{ .Build.ID }}"
    description: "go-evaluator"
    summary: "go-evaluator"

scoops:
  - repository:
      owner: arran4
      name: scoop-bucket
    ids: [csvfilter, jsonlfilter, jsontest, yamltest]
