// Generated by github.com/arran4/go-subcommand/cmd/gosubc

package main

import (
	"flag"
	"fmt"
	"os"
)

var _ Cmd = (*Yamltest)(nil)

type Yamltest struct {
	*RootCmd
	Flags       *flag.FlagSet
	expr        string
	files       []string
	SubCommands map[string]Cmd
}

func (c *Yamltest) Usage() {
	err := executeUsage(os.Stderr, "yamltest_usage.txt", c)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Yamltest) Execute(args []string) error {
	if len(args) > 0 {
		if cmd, ok := c.SubCommands[args[0]]; ok {
			return cmd.Execute(args[1:])
		}
	}
	err := c.Flags.Parse(args)
	if err != nil {
		return NewUserError(err, fmt.Sprintf("flag parse error %s", err.Error()))
	}
	remainingArgs := c.Flags.Args()
	// Handle vararg files
	{
		varArgStart := 0
		if varArgStart > len(remainingArgs) {
			varArgStart = len(remainingArgs)
		}
		varArgs := remainingArgs[varArgStart:]
		c.files = varArgs
	}

	YamlTest(c.expr, c.files...)

	return nil
}

func (c *RootCmd) NewYamltest() *Yamltest {
	set := flag.NewFlagSet("yamltest", flag.ContinueOnError)
	v := &Yamltest{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]Cmd),
	}

	set.StringVar(&v.expr, "e", "", "Expression")
	set.Usage = v.Usage

	return v
}
